### ISSUE TITLE
If multiple join/leave so not play TTS or only for one of them

### ISSUE THREAD

**Issue by henriklb** [ToFran/Smart_TTS#1]
If two users join/leave the channel at the same time the TTS sound does not play at all or only for one of them.  tsclient 3.1.6

**Comment by tofran** [comment]
Hello,
This behavior is not a problem from this soundpack, it happens with every TTS soundpacks, including the default ones provided by TeamSpeak.

It can only be fixed by the TeamSpeak developers. You can raise awareness of your problem @ `forum.teamspeak.com`.

Although I think it is an intended behavior and not a bug, here's why:
Imagine that 40 users join your channel. You would need to listen to the TTS for an eternity, waiting for it to finish.
The easier way - the current way -  is to just call the system TTS every time an action happens. So there is no TTS wait list and the maximum time you hear it speaking is duration of the last action.

**Comment by henriklb** [comment]
Thank you for your insight, Closed
